# Generated by Django 3.0.2 on 2020-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200321_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
