# Generated by Django 3.0.2 on 2020-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='summary_pl',
        ),
        migrations.AddField(
            model_name='job',
            name='summary_en',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
