# Generated by Django 3.1 on 2021-10-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200326_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
