# Generated by Django 3.1 on 2021-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_skill_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
