# Generated by Django 3.0.2 on 2020-03-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('text_pl', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_description', to='projects.Translation')),
                ('short_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_short_description', to='projects.Translation')),
                ('title_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_title', to='projects.Translation')),
            ],
        ),
    ]
