# Generated by Django 3.0.2 on 2020-03-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hyperlink',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
