# Generated by Django 3.0.2 on 2020-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery_image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_image4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
