# Generated by Django 3.0.2 on 2020-03-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200324_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hyperlink_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_hyperling_title', to='projects.Translation'),
        ),
    ]
