# Generated by Django 3.0.2 on 2020-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_hyperlink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gallery_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery_image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
