# Generated by Django 3.0.2 on 2020-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_second_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
