# Generated by Django 3.0.2 on 2020-03-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_translaton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translaton',
            new_name='Translation',
        ),
    ]
